name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        # Install package in editable mode
        pip install -e .
    
    - name: Create directory structure
      run: |
        mkdir -p projects/hybrid_llm_scraper/tests
        mkdir -p projects/hybrid_llm_scraper/src/scraper
        mkdir -p projects/hybrid_llm_scraper/src/pipeline
    
    - name: Run tests
      run: |
        cd projects/hybrid_llm_scraper
        PYTHONPATH=$PYTHONPATH:$(pwd) python -m pytest tests/ -v 